config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?


  get "/" => "users#index"
  resources :users do
    member do
      get :favo_page
    end
  end

  resources :sessions,only:[:new,:create,:destroy]
  resources :favorites, only: [:create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :image, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog

  validates :name,  presence: true, length: { maximum: 30 }
  before_validation { email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: true , on: :create

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  mount_uploader :user_image, ImageUploader
  attr_accessor :image_cache

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog,only:[:edit,:update,:show,:destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all.order(id: "DESC")
    @favorites = Favorite.all.order(id: "DESC")
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      ContactMailer.contact_mail(@blog).deliver
      redirect_to blogs_path,notice:"投稿が完了しました。"
    else
      render new_blog_path
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path,notice: "投稿を削除しました。"
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path,notice: "編集が完了しました"
    else
      render 'edit'
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:content,:image,:image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def authenticate_user
    @blog = Blog.find(params[:id])
    unless current_user.id == @blog.user.id
      flash[:notice] = "編集、削除の権限はありません"
      redirect_to blogs_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path , notice: "#{favorite.blog.user.name}さんの投稿にいいね！をしました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path , notice: "#{favorite.blog.user.name}さんの投稿のいいね！を取り消しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] ="ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice]= 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path , notice: "新規登録が完了しました"
    else
      render 'index'
    end
  end

  def show
    @user = User.find(params[:id])
    @blogs = current_user.blogs.all.order(id: "DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to edit_user_path, notice: "編集が完了しました"
    else
      render 'edit'
    end
  end

  def favo_page
    @user = User.find(params[:id])
    @favorites = current_user.favorite_blogs.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email,
                                 :password,
                                 :password_confirmation,
                                 :profile,
                                 :user_image, :user_image_cache)
  end

  def check_user
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:notice] = "編集権限がありません"
      redirect_to blogs_path
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' ||action_name =='confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, url: choose_new_or_edit, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <img id="img_prev" src="#" class='hidden blog_img_prev' />
    <%= image_tag(@blog.image.url, class: "blog_image　rm_img") if @blog.image.url %>
    <%= form.file_field :image, class: "submit_image", id: "post_img" %>
    <%= form.hidden_field :image_cache %>
    <br>
    <%= form.text_area :content, placeholder: "投稿する内容", id: "textarea", size: '30x3' %>
  </div>
  <br>
  <%= form.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/blogs/confirm.html.erb
<h1>下記の内容で投稿します。よろしいですか？</h1>

<%= form_with(model: @blog, url: blogs_path , local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <h2>投稿内容</h2>
  <p><%= @blog.content %></p>
  <%= image_tag @blog.image.url,class: "blog_image" %>
  <br>
  <%= form.submit  "投稿する。" , class: "submit btn btn-success" %>
<% end %>

<%= form_with(model: @blog , url: new_blog_path,local: true,method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit '戻る',name: 'back' %>
<% end %>
</div>

app/views/blogs/edit.html.erb
<div class="edit">
  <%= render 'form' %>
  <br>
  <%= link_to '戻る', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div>
  <% @blogs.each do |blog| %>
    <div class="index_container">
      <header class="index_header">
        <%= image_tag blog.user.user_image.url ,class: "index_icon" if blog.user.user_image.present?  %>
        <%= link_to "#{blog.user.name}", user_path(blog.user.id) %>
      </header>

      <body>
       <div class="index_image_area">
        <%= link_to blog_path(blog) do %>
         <%= image_tag blog.image.url, class: "blog_image" %>
        <% end %>
        </div>
       </body>
     </div>
   <% end %>
</div>

app/views/blogs/new.html.erb
<div class="blogs_new">
  <h1>今日何があった？</h1>
  <%= render 'form' , blog: @blog %>

  <%= link_to "入力内容をリセットする", "/blogs/new", data: {confirm: '本当にリセットしますか?'}  %>
</div>

app/views/blogs/show.html.erb
<div class="index_container">
  <header class="index_header">
    <%= image_tag @blog.user.user_image.url ,class: "index_icon" if @blog.user.user_image.present?  %>
    <%= @blog.user.name %>
  </header>

  <body>
  <div class="index_image_area">
    <%= image_tag @blog.image.url , class: "blog_image" %>
  </div>
  <div class="show_content">
    <strong><%= @blog.user.name %></strong>
    <%= simple_format(@blog.content) %>
  </div>
  <div class="favorite">
    <% unless @blog.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'いいね！を解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'いいね！をする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% else %>
      <%= link_to '編集する', edit_blog_path(@blog.id) %>
      <%= link_to '削除する', blog_path(@blog.id), method: :delete, data: {confirm: '本当に削除してもよろしいですか?'}%>
    <% end %>
  </div>
  </body>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstClone</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>
  <% if logged_in? %>
    <header class="header">
      <ul class="top_ul">
       <!-- TOP画像は公式よりDL -->
        <li id="li_top"><%= link_to image_tag('top.png',size: '40x40'), blogs_path %></li>
        <li id="li_end"><%= link_to image_tag('user.png',size: '40x40'), user_path(current_user.id) %></li>
        <li><%= link_to image_tag('favo.jpeg',size: '40x40'),favo_page_user_path(current_user.id) %></li>
        <li><%= link_to image_tag('blog.jpeg',size: '40x40'),new_blog_path %></li>
      </ul>
    </header>
  <% end %>

  <body>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </div>
  </body>
  <% unless logged_in? %>
    <footer>
     <%= link_to "利用規約とかをリンクさせるところ", '#' %>
    </footer>
  <% end %>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_edit">
    <table class="user_edit_table">
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name, size: 30 %></td>
      </tr>

      <tr>
        <th><%= f.label :profile %></th>
        <td><%= f.text_area :profile, size: "29x4", id: "textarea" %></td>
      </tr>

      <tr>
        <th><%= f.label :image %></th>
        <td>
          <img id="img_prev" src="#" class='hidden user_img_prev' />
          <%= image_tag(@user.user_image.url, class: "avater rm_img") if @user.user_image.url %>
          <%= f.file_field :user_image , id: "post_img"%>
        </td>
        <%= f.hidden_field :user_image_cache %>

      </tr>
    </table>

    <div class="form_buttom">
      <%= f.submit "送信する" %>
    </div>
  </div>
<% end %>

app/views/users/favo_page.html.erb
<h1 class="favo_page_h1">いいね！した投稿一覧</h1>

<div class="favo_page">
  <% @favorites.each do |favo| %>
    <div class="favo_page_image_area">
      <%= link_to blog_path(favo) do %>
        <%= image_tag favo.image.url ,class: "favo_image" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="creat_user_form">
  <%= form_with(model:@user,local: true) do |f| %>
    <h1 class="creat_user_form_title">Inst Clone</h1>
    <div class="input_name">
      <%= f.text_field :name,placeholder: "お名前",size: 30 %>
   </div>

   <div class="input_email">
     <%= f.email_field :email,placeholder: "メールアドレス",size: 30 %>
    </div>

   <div class="input_password">
    <%= f.password_field :password,placeholder: "パスワード",size: 30 %>
   </div>

   <div class="input_re_password">
     <%= f.password_field :password_confirmation,placeholder: "パスワードを再入力",size: 30 %>
    </div>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <strong><%= pluralize(@user.errors.count, "件のエラーがあります。") %></strong>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class="errors_msg"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


   <%= f.submit "アカウント登録" ,class: "creat_submit btn btn-success" %>

  <% end %>

    <p>アカウントはお持ちですか？</p>
   <%= link_to "ログインはこちらから" ,'sessions/new' %>
 </div>

app/views/users/show.html.erb
<div class="user_show">
  <div class="user_area">
  <div class="user_image">
    <%= image_tag(@user.user_image.url, class: "avater") if @user.user_image.present? %>
  </div>

  <div class="user_data clearfix">
    <div class="user_date_show"></div>
    <p><%= @user.name %></p>
    <% if @user.id == current_user.id %>
      <%= link_to 'プロフィールを編集', edit_user_path(@user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% end %>
    <div class="user_profile">
      <%= @user.profile %>
    </div>
  </div>
  </div>

  <div>
    <% @blogs.each do |blog| %>
      <div class="my_index_image_area">
        <%= link_to blog_path(blog) do %>
          <%= image_tag blog.image.url, class: "myblog_image" %>
        <% end %>
      </div>
    <% end %>
  </div>

</div>